require 'aws-sdk'
# load 'env.rb'

task :update do
  service = AWS::S3.new
  bucket = service.buckets['pinguin-radio']

  [
    'js/application.js'
  ].each do |path|
    puts "Uploading #{path}..."
    bucket.objects[path].write(File.read(path), {:acl => :public_read})
  end
end
